<?php
$ScrollsOfMagic = $this->ScrollsOfMagic;
$SiegeWeapons = $this->SiegeWeapons;
$warriors = $this->warriors;
$userarmory = $this->userarmory;
$gamethings = $this->gamethings;
$userWarriors = $this->userWarriors;
$userSiegeWeapons = $this->userSiegeWeapons;
$Userscrollsofmagic = $this->Userscrollsofmagic;
?>

<br><br><br><br>
<ul class="nav nav-tabs">
    <li class="active" style="width: 25%"><a data-toggle="tab" href="#warriors" style="text-align: center"><b>Воины</b></a></li>
    <li style="width: 25%"><a data-toggle="tab" href="#arsenal" style="text-align: center"><b>Арсенал </b></a></li>
    <li style="width: 25%"><a data-toggle="tab" href="#SiegeWeapons" style="text-align: center"><b> Осадное оружие </b></a></li>
    <li style="width: 25%"><a data-toggle="tab" href="#Magic" style="text-align: center"><b> Свитки магии </b></a></li>
</ul>

<div class="tab-content">
    <div id="warriors" class="tab-pane fade in active">
        <div class="container">
            <h4 style="text-align: center">Армия</h4>
            <hr>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th hidden>id</th>
                            <th style="text-align: center"><br>Тип воина</th>
                            <th style="text-align: center"><br>Атака</th>
                            <th style="text-align: center"><br>Защита</th>
                            <th style="text-align: center"><br>Жизнь</th>
                            <th style="text-align: center"><br>Количество</th>
                        </tr>
                    </thead>
                    <tbody>

                        <?php
                        $z = 0;
                        for ($i = 0; $i < count($warriors); $i++) {
                            ?>
                            <tr>
                                <td hidden><?= $warriors[$i]['idwarriors'] ?></td>
                                <td style="text-align: center"><img src="<?= $warriors[$i]['imgwarriors'] ?>" width="70" height="138"><br><?= $warriors[$i]['namewarriors'] ?></td>
                                <td style="text-align: center"><h5><?= $warriors[$i]['attackwarriors'] ?></h5></td>
                                <td style="text-align: center"><h5><?= $warriors[$i]['deffencewarriors'] ?></h5></td>
                                <td style="text-align: center"><h5><?= $warriors[$i]['hplifewarriors'] ?></h5></td>
                                <?php
                                if (isset($userWarriors[$z]['id_warriors'])) {
                                    if ($warriors[$i]['idwarriors'] === $userWarriors[$z]['id_warriors']) {
                                        ?> 
                                        <td style="text-align: center"><h5><?= $userWarriors[$z]['count_warriors'] ?></h5></td>



                                        <?php
                                        $z++;
                                    } else {
                                        ?><td style="text-align: center"><h5>0</h5></td> <?php } ?>
                                    <?php
                                } else {
                                    $z = 0;
                                    ?> <td style="text-align: center"><h5>0</h5></td> <?php } ?>

                            </tr>

                        <?php } ?>

                    </tbody>

                </table>


            </div>

        </div>
    </div>

    <div id="arsenal" class="tab-pane fade">

        <div class="container">
            <h4 style="text-align: center">Оружие</h4>
            <hr>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th hidden>id</th>
                            <th style="text-align: center"><br>Тип оружия</th>
                            <th style="text-align: center"><br>Атака</th>
                            <th style="text-align: center"><br>Защита</th>
                            <th style="text-align: center"><br>Прочность</th>
                            <th style="text-align: center"><br>Количество</th>
                        </tr>
                    </thead>
                    <tbody>

                        <?php
                        $z = 0;
                        for ($i = 0; $i < count($gamethings); $i++) {
                            ?>
                            <tr>
                                <td hidden><?= $gamethings[$i]['things_id'] ?></td>
                                <td style="text-align: center"><img src="<?= $gamethings[$i]['img_things'] ?>" width="60" height="73"><br><?= $gamethings[$i]['name_things'] ?></td>
                                <td style="text-align: center"><h5><?= $gamethings[$i]['attack_things'] ?></h5></td>
                                <td style="text-align: center"><h5><?= $gamethings[$i]['defence_things'] ?></h5></td>
                                <td style="text-align: center"><h5><?= $gamethings[$i]['strength_things'] ?></h5></td>


                                <?php if ($gamethings[$i]['things_id'] === $userarmory[$z]['id_things']) {
                                    ?> 
                                    <td style="text-align: center"><h5><?= $userarmory[$z]['count_armory'] ?></h5></td>



                                    <?php
                                    $z++;
                                } else {
                                    ?><td style="text-align: center"><h5>0</h5></td> <?php } ?>
                            </tr>
                        <?php } ?>

                    </tbody>
                </table>


            </div>

        </div>

    </div>





    <div id="SiegeWeapons" class="tab-pane fade">

        <div class="container">
            <h4 style="text-align: center">Осадное орежие</h4>
            <hr>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th hidden>id</th>
                            <th style="text-align: center"><br>Тип осадного оружия</th>
                            <th style="text-align: center"><br>Атака</th>
                            <th style="text-align: center"><br>Защита</th>
                            <th style="text-align: center"><br>Количество</th>
                        </tr>
                    </thead>
                    <tbody>

                        <?php
                        $z = 0;
                        for ($i = 0; $i < count($SiegeWeapons); $i++) {
                            ?>
                            <tr>
                                <td hidden><?= $SiegeWeapons[$i]['idSiegeWeapons'] ?></td>
                                <td style="text-align: center"><img src="<?= $SiegeWeapons[$i]['ImgSiegeWeapons'] ?>" width="70" height="83"><br><?= $SiegeWeapons[$i]['NameSiegeWeapons'] ?></td>
                                <td style="text-align: center"><h5><?= $SiegeWeapons[$i]['AttackSiegeWeapons'] ?></h5></td>
                                <td style="text-align: center"><h5><?= $SiegeWeapons[$i]['DeffenceSiegeWeapons'] ?></h5></td>
                                <?php
                                if (isset($userSiegeWeapons[$z]['SiegeWeaponsId'])) {
                                    if ($SiegeWeapons[$i]['idSiegeWeapons'] === $userSiegeWeapons[$z]['SiegeWeaponsId']) {
                                        ?> 
                                        <td style="text-align: center"><h5><?= $userSiegeWeapons[$z]['UserSiegeWeaponsCount'] ?></h5></td>



                                        <?php
                                        $z++;
                                    } else {
                                        ?><td style="text-align: center"><h5>0</h5></td> <?php } ?>
                                    <?php
                                } else {
                                    $z = 0;
                                    ?> <td style="text-align: center"><h5>0</h5></td> <?php } ?>
                            </tr>
                        <?php } ?>

                    </tbody>

                </table>


            </div>

        </div>

    </div>


    <div id="Magic" class="tab-pane fade">
        <div class="container">
            <h4 style="text-align: center">Свитки магии</h4>
            <hr>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th hidden>id</th>
                            <th style="text-align: center"><br>Тип свитка</th>
                            <th style="text-align: center"><br>Атака</th>
                            <th style="text-align: center"><br>Защита</th>
                            <th style="text-align: center"><br>Стоимость MP</th>
                            <th style="text-align: center"><br>Количество</th>
                        </tr>
                    </thead>
                    <tbody>

                        <?php $z = 0; 
                        for ($i = 0; $i < count($ScrollsOfMagic); $i++) { ?>
                            <tr>
                                <td hidden><?= $ScrollsOfMagic[$i]['idScrollsOfMagic'] ?></td>
                                <td style="text-align: center"><img src="<?= $ScrollsOfMagic[$i]['ImgScrollsOfMagic'] ?>" width="70" height="83"><br><?= $ScrollsOfMagic[$i]['NameScrollsOfMagic'] ?></td>
                                <td style="text-align: center"><h5><?= $ScrollsOfMagic[$i]['AttackScrollsOfMagic'] ?></h5></td>
                                <td style="text-align: center"><h5><?= $ScrollsOfMagic[$i]['DeffenceScrollsOfMagic'] ?></h5></td>
                                <td style="text-align: center"><h5><?= $ScrollsOfMagic[$i]['scrollsofmagicMP'] ?></h5></td>
                                <?php
                                if (isset($Userscrollsofmagic[$z]['scrollsofmagicId'])) {
                                    if ($SiegeWeapons[$i]['idSiegeWeapons'] === $Userscrollsofmagic[$z]['scrollsofmagicId']) {
                                        ?> 
                                        <td style="text-align: center"><h5><?= $Userscrollsofmagic[$z]['scrollsofmagicCount'] ?></h5></td>



                                        <?php
                                        $z++;
                                    } else {
                                        ?><td style="text-align: center"><h5>0</h5></td> <?php } ?>
                                    <?php
                                } else {
                                    $z = 0;
                                    ?> <td style="text-align: center"><h5>0</h5></td> <?php } ?>
                            </tr>
                        <?php } ?>

                    </tbody>

                </table>


            </div>

        </div>

    </div>






</div>








<td background="<?= $this->basePath('img/ramka/border_v.gif') ?>"><img src="<?= $this->basePath('img/null.gif') ?>"></td>
