<?php
$this->headTitle('Регистрация');

$this->mainMenu()->setActiveItemId('registration-form');

//$this->pageBreadcrumbs()->setItems([
//            'Home'=>$this->url('home'),
//            'Manage Users'=>$this->url('users'),
//            'Add User'=>$this->url('users', ['action'=>'add'])
//            ]);

$form->get('email')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'name@example.com'
]);

$form->get('full_name')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'John Doe'
]);

$form->get('uFirstName')->setAttributes([
    'class' => 'form-control'
]);
$form->get('uLastName')->setAttributes([
    'class' => 'form-control'
]);

$form->get('uGender')->setAttributes([
    'class' => 'form-control'
]);

$form->get('uRace')->setAttributes([
    'class' => 'form-control'
]);

$form->get('password')->setAttributes([
    'class' => 'form-control'
]);

$form->get('confirm_password')->setAttributes([
    'class' => 'form-control'
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);

$form->prepare();
?>

<div style="text-align: center">
    <h1>Регистрация нового пользователя</h1>

    <p>
        Please fill out the following form and click the <i>Create</i> button.
    </p>

    <div class="row">
        <div class="col-md-6">
            <?= $this->form()->openTag($form); ?>

            <div class="form-group">
                <?= $this->formLabel($form->get('email')); ?>
                <?= $this->formElement($form->get('email')); ?>
                <?= $this->formElementErrors($form->get('email')); ?>                  
            </div>

            <div class="form-group">
                <?= $this->formLabel($form->get('full_name')); ?>
                <?= $this->formElement($form->get('full_name')); ?>
                <?= $this->formElementErrors($form->get('full_name')); ?>                  
            </div>

            <div class="form-group">
                <?= $this->formLabel($form->get('uFirstName')); ?>
                <?= $this->formElement($form->get('uFirstName')); ?>
                <?= $this->formElementErrors($form->get('uFirstName')); ?>                  
            </div>

            <div class="form-group">
                <?= $this->formLabel($form->get('uLastName')); ?>
                <?= $this->formElement($form->get('uLastName')); ?>
                <?= $this->formElementErrors($form->get('uLastName')); ?>                  
            </div>

            <div class="form-group">
                <?= $this->formLabel($form->get('uGender')); ?>
                <?= $this->formElement($form->get('uGender')); ?>
                <?= $this->formElementErrors($form->get('uGender')); ?>                  
            </div>

            <div class="form-group">
                <?= $this->formLabel($form->get('uRace')); ?>
                <?= $this->formElement($form->get('uRace')); ?>
                <?= $this->formElementErrors($form->get('uRace')); ?>                  
            </div>

            <div class="form-group">
                <?= $this->formLabel($form->get('password')); ?>
                <?= $this->formElement($form->get('password')); ?>
                <?= $this->formElementErrors($form->get('password')); ?>                  
            </div>

            <div class="form-group">
                <?= $this->formLabel($form->get('confirm_password')); ?>
                <?= $this->formElement($form->get('confirm_password')); ?>
                <?= $this->formElementErrors($form->get('confirm_password')); ?>                  
            </div>


            <?= $this->formElement($form->get('submit')); ?>

            <?= $this->form()->closeTag(); ?>
        </div>    
    </div>   

</div>